version: '3.8'

services: 
  localstack:
    image: localstack/localstack:latest
    network_mode: bridge
    environment: 
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=lambda,s3
      - DEBUG=1
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
    ports: 
      - '4566-4597:4566-4597'    
    volumes: 
      - ${TEMPDIR:-/tmp/localstack}:/temp/localstack
      - /var/run/docker.sock:/var/run/docker.sock