service: service-name

frameworkVersion: '2 || 3'
configValidationMode: off

provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'local'}
  runtime: nodejs14.x
  memorySize: 128
  timeout: 10
  profile: profile-name
  lambdaHashingVersion: 20201221
  versionFunctions: false

  environment:
    ${file(${self:custom.projectDir.configs}/${sls:stage}.yml)}

package:
  individually: true 
  excludeDevDependencies: true
  
functions: 
  ${file(${self:custom.projectDir.modules}/functions.yml)}

resources:
  Resources:
    # Buckets
    CertifiedEmitterBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.buckets.main}

custom:
  # Buckets
  buckets: 
    main: ${sls:stage}-bucket-name
  # Project Dir
  projectDir: 
    modules: ./modules
    configs: ./configs
  # Webpack config
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: false
    packager: 'yarn'
  # Localstack config
  localstack:
    debug: true
    stages:
      - local
    endpointFile: ./configs/endpoints.json

plugins:
  - serverless-webpack
  - serverless-localstack