service: certified-emitter

frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name:	certified-emitter-bucket

functions:
  certified-emitter-function:
    name: ${sls:stage}-certified-emitter-function
    description: Função responsável pela emissão dos certificados
    handler: ./certified-emitter-function/index.handler
    timeout: 30
    memorySize: 128
    runtime: nodejs14.x
